name: Daily SCA Scan on Main Branch 

# Schedule the workflow to run every 24 hours 
on: 
  schedule: 
    - cron: '0 0 * * *'  # Runs every day at midnight UTC 

  # Also allow manual triggering of the workflow 
  workflow_dispatch: 

permissions: 
  security-events: write  # Grant permission to upload SARIF files for Code Scanning 
  contents: read  # Grant permission to read the contents of the repository 

jobs: 
  daily_scan: 
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu environment 

    steps: 
      # Step 1: Install the Lacework CLI and SCA component 
      - name: Install Lacework CLI 
        run: | 
          # Download and install the Lacework CLI using a shell script 

          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash 
          # Configure the Lacework CLI with account, API key, and secret from GitHub secrets 
          lacework configure -a ${{ secrets.LW_ACCOUNT }}.lacework.net -k ${{ secrets.LW_API_KEY }} -s ${{ secrets.LW_API_SECRET }} --noninteractive 
          # Install the Software Composition Analysis (SCA) component 
          lacework component install sca 

      # Step 2: Check out the main branch 
      - name: Checkout main branch 
        uses: actions/checkout@v3  # Use the checkout action to pull the main branch code 
        with: 
          ref: main  # Specify the main branch 
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication 

      # Step 3: Run the Lacework SCA scan on the main branch and generate SARIF output 
      - name: Run Lacework SCA Scan on Main Branch 
        run: lacework sca scan ./ -f sarif -o lacework-scan.sarif 
        # Scan the main branch code, output in SARIF format, and save to lacework-scan.sarif 

      # Step 4: Upload the SARIF file to GitHub Code Scanning 
      - name: Upload SARIF to GitHub Code Scanning 
        uses: github/codeql-action/upload-sarif@v3  # Use the GitHub action to upload SARIF 
        with: 
          sarif_file: lacework-scan.sarif  # Path to the SARIF file 
